spring.application.name=Transfer-API

server.port=8290

logging.level.root=INFO
logging.level.com.Transfer.API=INFO
logging.level.org.springframework=WARN



#=======================================================
#          DATABASE CONFIGURATION
#=======================================================

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

#=======================================================
#           APPLICATION PROPERTIES
#=======================================================

transaction.fee.rate=0.005
max.transaction.fee=100
commission.rate=0.2



#=======================================================
#          SWAGGER IMPLEMENTATION
#=======================================================

# Logging
logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG

# SpringDoc/Swagger Config
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
